### PR TITLE
Using FakePlayer class for machine PlayerEntity

### LINKED ISSUE #321: Enderic Lazser killing creature causes server crash
### Issue description

Placing an Enderic Lazser and killing an entity results in a crash.

Test 1. Zombie Vanilla = Crash
Test 2. Pokemon from Cobblemon = Crash
Test 3. Zombie again = Crash

We have an extreemly moded version of minecraft in a custom modpack with Oritech, CC Tweaks and Cobblemon as the only main two "core" mods. Everything else is QOL, furniture or crops of some sort, very small changes that I don't imagine would be causing this.

### Steps to reproduce

1. Place Enderic Lazser
2. Spawn a Zombie
3. Server Crashes

### Minecraft version

1.21.1 (Latest)

### Platform

Fabric

### Loader version

0.16.13

### Fabric API version

0.115.4+1.21.1

### Oritech version

0.14.5

### Other relevant versions

See Images for list of all mods in the pack. Feel free to contact me and I can give you a copy of the pack for a test environment if needed! From the logs however it looks largely irrelevant. 

Image
Image

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

[crash-2025-04-14_18.03.39-server.txt](https://github.com/user-attachments/files/19744266/crash-2025-04-14_18.03.39-server.txt)

### PR DESCRIPTION
**Pull request by jshipley**
Fixes #321

Using FakePlayer classes that extend ServerPlayerEntity for machine PlayerEntity classes.

This also fixes the crash caused by Backpacked trying to cast the laser's PlayerEntity to a ServerPlayerEntity.

I did this with Architectury's @ExpectPlatform and Impl class detection. Let me know if you'd rather have it done the way you're doing the Item/Fluid/Energy API xplat classes.

### CODE REVIEW

**Comment by Rearth** [comment]
Cool stuff, really loving this approach, this will make compat with some mods much easier. Is there a reason for the destroyer block not using the inventory fake player variant aswell?

**Comment by jshipley** [comment]
There's no reason. I'll update the block destroyer as well.

File: common/src/main/java/rearth/oritech/block/entity/interaction/DestroyerBlockEntity.java [hunk 1]
```diff
@@ -118,18 +120,8 @@ protected boolean hasWorkAvailable(BlockPos toolPosition) {
...
-                    return false;
-                }
-                
-                @Override
-                public boolean isCreative() {
-                    return false;
-                }
-            };
+        if (destroyerPlayerEntity == null && world instanceof ServerWorld serverWorld) {
+            destroyerPlayerEntity = FakeMachinePlayer.create(serverWorld, new GameProfile(UUID.randomUUID(), "oritech_destroyer"));
```
Comment (jshipley) [inline common/src/main/java/rearth/oritech/block/entity/interaction/DestroyerBlockEntity.java:124]: It is already using the FakeMachinePlayer for the DestroyerBlockEntity

Comment (Rearth) [reply common/src/main/java/rearth/oritech/block/entity/interaction/DestroyerBlockEntity.java:124]: Sorry, I meant the inventory variant of the FakeMachinePlayer. E.g. the method variant that also takes the inventory as parameter
